export const skippedResources = {
  quantserve: null,
  adzerk: null,
  doubleclick: null,
  adition: null,
  exelator: null,
  sharethrough: null,
  "cdn.api.twitter": null,
  "google-analytics": null,
  googletagmanager: null,
  usefathom: null,
  google: null,
  fontawesome: null,
  facebook: null,
  analytics: null,
  optimizely: null,
  clicktale: null,
  mixpanel: null,
  zedo: null,
  clicksor: null,
  tiqcdn: null,
  livereload: null,
  "cdn.jsdelivr.net": null,
  "googlesyndication.com": null,
  "adservice.google.com": null,
  "client.crisp.chat": null,
  "widget.intercom.io": null,
};

export const blockedResourceTypes = {
  media: null,
  font: null,
  texttrack: null,
  object: null,
  beacon: null,
  csp_report: null,
  websocket: null,
  // script: null,
  preflight: null,
  image: null,
  imageset: null,
  ping: null,
};
